
export const COUNTRIES = ['India'];

export const INDIA_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 
  'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 
  'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 
  'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 
  'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 
  'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry'
];

export const STATE_DISTRICTS: Record<string, string[]> = {
  'Andhra Pradesh': ['Anantapur', 'Chittoor', 'East Godavari', 'Guntur', 'Krishna', 'Kurnool', 'Prakasam', 'Srikakulam', 'Sri Potti Sriramulu Nellore', 'Visakhapatnam', 'Vizianagaram', 'West Godavari', 'YSR Kadapa'],
  'Arunachal Pradesh': ['Anjaw', 'Changlang', 'Dibang Valley', 'East Kameng', 'East Siang', 'Kamle', 'Kra Daadi', 'Kurung Kumey', 'Lepa Rada', 'Lohit', 'Longding', 'Lower Dibang Valley', 'Lower Siang', 'Lower Subansiri', 'Namsai', 'Pakke Kessang', 'Papum Pare', 'Shi Yomi', 'Siang', 'Tawang', 'Tirap', 'Upper Siang', 'Upper Subansiri', 'West Kameng', 'West Siang'],
  'Assam': ['Baksa', 'Barpeta', 'Biswanath', 'Bongaigaon', 'Cachar', 'Charaideo', 'Chirang', 'Darrang', 'Dhemaji', 'Dhubri', 'Dibrugarh', 'Dima Hasao', 'Goalpara', 'Golaghat', 'Hailakandi', 'Hojai', 'Jorhat', 'Kamrup', 'Kamrup Metropolitan', 'Karbi Anglong', 'Karimganj', 'Kokrajhar', 'Lakhimpur', 'Majuli', 'Morigaon', 'Nagaon', 'Nalbari', 'Sivasagar', 'Sonitpur', 'South Salmara-Mankachar', 'Tinsukia', 'Udalguri', 'West Karbi Anglong'],
  'Bihar': ['Araria', 'Arwal', 'Aurangabad', 'Banka', 'Begusarai', 'Bhagalpur', 'Bhojpur', 'Buxar', 'Darbhanga', 'East Champaran', 'Gaya', 'Gopalganj', 'Jamui', 'Jehanabad', 'Kaimur', 'Katihar', 'Khagaria', 'Kishanganj', 'Lakhisarai', 'Madhepura', 'Madhubani', 'Munger', 'Muzaffarpur', 'Nalanda', 'Nawada', 'Patna', 'Purnia', 'Rohtas', 'Saharsa', 'Samastipur', 'Saran', 'Sheikhpura', 'Sheohar', 'Sitamarhi', 'Siwan', 'Supaul', 'Vaishali', 'West Champaran'],
  'Chhattisgarh': ['Balod', 'Baloda Bazar', 'Balrampur', 'Bastar', 'Bemetara', 'Bijapur', 'Bilaspur', 'Dantewada', 'Dhamtari', 'Durg', 'Gariaband', 'Gaurela-Pendra-Marwahi', 'Janjgir-Champa', 'Jashpur', 'Kabirdham', 'Kanker', 'Kondagaon', 'Korba', 'Koriya', 'Mahasamund', 'Mungeli', 'Narayanpur', 'Raigarh', 'Raipur', 'Rajnandgaon', 'Sukma', 'Surajpur', 'Surguja'],
  'Goa': ['North Goa', 'South Goa'],
  'Gujarat': ['Ahmedabad', 'Amreli', 'Anand', 'Aravalli', 'Banaskantha', 'Bharuch', 'Bhavnagar', 'Botad', 'Chhota Udepur', 'Dahod', 'Dang', 'Devbhumi Dwarka', 'Gandhinagar', 'Gir Somnath', 'Jamnagar', 'Junagadh', 'Kheda', 'Kutch', 'Mahisagar', 'Mehsana', 'Morbi', 'Narmada', 'Navsari', 'Panchmahal', 'Patan', 'Porbandar', 'Rajkot', 'Sabarkantha', 'Surat', 'Surendranagar', 'Tapi', 'Vadodara', 'Valsad'],
  'Haryana': ['Ambala', 'Bhiwani', 'Charkhi Dadri', 'Faridabad', 'Fatehabad', 'Gurugram', 'Hisar', 'Jhajjar', 'Jind', 'Kaithal', 'Karnal', 'Kurukshetra', 'Mahendragarh', 'Nuh', 'Palwal', 'Panchkula', 'Panipat', 'Rewari', 'Rohtak', 'Sirsa', 'Sonipat', 'Yamunanagar'],
  'Himachal Pradesh': ['Bilaspur', 'Chamba', 'Hamirpur', 'Kangra', 'Kinnaur', 'Kullu', 'Lahaul and Spiti', 'Mandi', 'Shimla', 'Sirmaur', 'Solan', 'Una'],
  'Jharkhand': ['Bokaro', 'Chatra', 'Deoghar', 'Dhanbad', 'Dumka', 'East Singhbhum', 'Garhwa', 'Giridih', 'Godda', 'Gumla', 'Hazaribagh', 'Jamtara', 'Khunti', 'Koderma', 'Latehar', 'Lohardaga', 'Pakur', 'Palamu', 'Ramgarh', 'Ranchi', 'Sahibganj', 'Seraikela-Kharsawan', 'Simdega', 'West Singhbhum'],
  'Karnataka': ['Bagalkot', 'Ballari', 'Belagavi', 'Bengaluru Rural', 'Bengaluru Urban', 'Bidar', 'Chamarajanagar', 'Chikkaballapur', 'Chikkamagaluru', 'Chitradurga', 'Dakshina Kannada', 'Davanagere', 'Dharwad', 'Gadag', 'Hassan', 'Haveri', 'Kalaburagi', 'Kodagu', 'Kolar', 'Koppal', 'Mandya', 'Mysuru', 'Raichur', 'Ramanagara', 'Shivamogga', 'Tumakuru', 'Udupi', 'Uttara Kannada', 'Vijayapura', 'Yadgir'],
  'Kerala': ['Alappuzha', 'Ernakulam', 'Idukki', 'Kannur', 'Kasaragod', 'Kollam', 'Kottayam', 'Kozhikode', 'Malappuram', 'Palakkad', 'Pathanamthitta', 'Thiruvananthapuram', 'Thrissur', 'Wayanad'],
  'Madhya Pradesh': ['Agar Malwa', 'Alirajpur', 'Anuppur', 'Ashoknagar', 'Balaghat', 'Barwani', 'Betul', 'Bhind', 'Bhopal', 'Burhanpur', 'Chhatarpur', 'Chhindwara', 'Damoh', 'Datia', 'Dewas', 'Dhar', 'Dindori', 'Guna', 'Gwalior', 'Harda', 'Hoshangabad', 'Indore', 'Jabalpur', 'Jhabua', 'Katni', 'Khandwa', 'Khargone', 'Mandla', 'Mandsaur', 'Morena', 'Narsinghpur', 'Neemuch', 'Niwari', 'Panna', 'Raisen', 'Rajgarh', 'Ratlam', 'Rewa', 'Sagar', 'Satna', 'Sehore', 'Seoni', 'Shahdol', 'Shajapur', 'Sheopur', 'Shivpuri', 'Sidhi', 'Singrauli', 'Tikamgarh', 'Ujjain', 'Umaria', 'Vidisha'],
  'Maharashtra': ['Ahmednagar', 'Akola', 'Amravati', 'Aurangabad', 'Beed', 'Bhandara', 'Buldhana', 'Chandrapur', 'Dhule', 'Gadchiroli', 'Gondia', 'Hingoli', 'Jalgaon', 'Jalna', 'Kolhapur', 'Latur', 'Mumbai City', 'Mumbai Suburban', 'Nagpur', 'Nanded', 'Nandurbar', 'Nashik', 'Osmanabad', 'Palghar', 'Parbhani', 'Pune', 'Raigad', 'Ratnagiri', 'Sangli', 'Satara', 'Sindhudurg', 'Solapur', 'Thane', 'Wardha', 'Washim', 'Yavatmal'],
  'Manipur': ['Bishnupur', 'Chandel', 'Churachandpur', 'Imphal East', 'Imphal West', 'Jiribam', 'Kakching', 'Kamjong', 'Kangpokpi', 'Noney', 'Pherzawl', 'Senapati', 'Tamenglong', 'Tengnoupal', 'Thoubal', 'Ukhrul'],
  'Meghalaya': ['East Garo Hills', 'East Jaintia Hills', 'East Khasi Hills', 'North Garo Hills', 'Ri Bhoi', 'South Garo Hills', 'South West Garo Hills', 'South West Khasi Hills', 'West Garo Hills', 'West Jaintia Hills', 'West Khasi Hills'],
  'Mizoram': ['Aizawl', 'Champhai', 'Hnahthial', 'Khawzawl', 'Kolasib', 'Lawngtlai', 'Lunglei', 'Mamit', 'Saiha', 'Saitual', 'Serchhip'],
  'Nagaland': ['Dimapur', 'Kiphire', 'Kohima', 'Longleng', 'Mokokchung', 'Mon', 'Noklak', 'Peren', 'Phek', 'Tuensang', 'Wokha', 'Zunheboto'],
  'Odisha': ['Angul', 'Balangir', 'Balasore', 'Bargarh', 'Bhadrak', 'Boudh', 'Cuttack', 'Deogarh', 'Dhenkanal', 'Gajapati', 'Ganjam', 'Jagatsinghpur', 'Jajpur', 'Jharsuguda', 'Kalahandi', 'Kandhamal', 'Kendrapara', 'Kendujhar', 'Khordha', 'Koraput', 'Malkangiri', 'Mayurbhanj', 'Nabarangpur', 'Nayagarh', 'Nuapada', 'Puri', 'Rayagada', 'Sambalpur', 'Sonepur', 'Sundargarh'],
  'Punjab': ['Amritsar', 'Barnala', 'Bathinda', 'Faridkot', 'Fatehgarh Sahib', 'Fazilka', 'Ferozepur', 'Gurdaspur', 'Hoshiarpur', 'Jalandhar', 'Kapurthala', 'Ludhiana', 'Mansa', 'Moga', 'Muktsar', 'Pathankot', 'Patiala', 'Rupnagar', 'Sahibzada Ajit Singh Nagar', 'Sangrur', 'Shahid Bhagat Singh Nagar', 'Sri Muktsar Sahib', 'Tarn Taran'],
  'Rajasthan': ['Ajmer', 'Alwar', 'Banswara', 'Baran', 'Barmer', 'Bharatpur', 'Bhilwara', 'Bikaner', 'Bundi', 'Chittorgarh', 'Churu', 'Dausa', 'Dholpur', 'Dungarpur', 'Hanumangarh', 'Jaipur', 'Jaisalmer', 'Jalore', 'Jhalawar', 'Jhunjhunu', 'Jodhpur', 'Karauli', 'Kota', 'Nagaur', 'Pali', 'Pratapgarh', 'Rajsamand', 'Sawai Madhopur', 'Sikar', 'Sirohi', 'Sri Ganganagar', 'Tonk', 'Udaipur'],
  'Sikkim': ['East Sikkim', 'North Sikkim', 'South Sikkim', 'West Sikkim'],
  'Tamil Nadu': ['Ariyalur', 'Chengalpattu', 'Chennai', 'Coimbatore', 'Cuddalore', 'Dharmapuri', 'Dindigul', 'Erode', 'Kallakurichi', 'Kancheepuram', 'Kanyakumari', 'Karur', 'Krishnagiri', 'Madurai', 'Mayiladuthurai', 'Nagapattinam', 'Namakkal', 'Nilgiris', 'Perambalur', 'Pudukkottai', 'Ramanathapuram', 'Ranipet', 'Salem', 'Sivaganga', 'Tenkasi', 'Thanjavur', 'Theni', 'Thoothukudi', 'Tiruchirappalli', 'Tirunelveli', 'Tirupathur', 'Tiruppur', 'Tiruvallur', 'Tiruvannamalai', 'Tiruvarur', 'Vellore', 'Viluppuram', 'Virudhunagar'],
  'Telangana': ['Adilabad', 'Bhadradri Kothagudem', 'Hyderabad', 'Jagtial', 'Jangaon', 'Jayashankar Bhupalpally', 'Jogulamba Gadwal', 'Kamareddy', 'Karimnagar', 'Khammam', 'Kumuram Bheem Asifabad', 'Mahabubabad', 'Mahabubnagar', 'Mancherial', 'Medak', 'Medchal-Malkajgiri', 'Mulugu', 'Nagarkurnool', 'Nalgonda', 'Narayanpet', 'Nirmal', 'Nizamabad', 'Peddapalli', 'Rajanna Sircilla', 'Rangareddy', 'Sangareddy', 'Siddipet', 'Suryapet', 'Vikarabad', 'Wanaparthy', 'Warangal Rural', 'Warangal Urban', 'Yadadri Bhuvanagiri'],
  'Tripura': ['Dhalai', 'Gomati', 'Khowai', 'North Tripura', 'Sepahijala', 'South Tripura', 'Unakoti', 'West Tripura'],
  'Uttar Pradesh': ['Agra', 'Aligarh', 'Ambedkar Nagar', 'Amethi', 'Amroha', 'Auraiya', 'Ayodhya', 'Azamgarh', 'Baghpat', 'Bahraich', 'Ballia', 'Balrampur', 'Banda', 'Barabanki', 'Bareilly', 'Basti', 'Bhadohi', 'Bijnor', 'Budaun', 'Bulandshahr', 'Chandauli', 'Chitrakoot', 'Deoria', 'Etah', 'Etawah', 'Farrukhabad', 'Fatehpur', 'Firozabad', 'Gautam Buddh Nagar', 'Ghaziabad', 'Ghazipur', 'Gonda', 'Gorakhpur', 'Hamirpur', 'Hapur', 'Hardoi', 'Hathras', 'Jalaun', 'Jaunpur', 'Jhansi', 'Kannauj', 'Kanpur Dehat', 'Kanpur Nagar', 'Kasganj', 'Kaushambi', 'Kushinagar', 'Lakhimpur Kheri', 'Lalitpur', 'Lucknow', 'Maharajganj', 'Mahoba', 'Mainpuri', 'Mathura', 'Mau', 'Meerut', 'Mirzapur', 'Moradabad', 'Muzaffarnagar', 'Pilibhit', 'Pratapgarh', 'Prayagraj', 'Raebareli', 'Rampur', 'Saharanpur', 'Sambhal', 'Sant Kabir Nagar', 'Shahjahanpur', 'Shamli', 'Shravasti', 'Siddharthnagar', 'Sitapur', 'Sonbhadra', 'Sultanpur', 'Unnao', 'Varanasi'],
  'Uttarakhand': ['Almora', 'Bageshwar', 'Chamoli', 'Champawat', 'Dehradun', 'Haridwar', 'Nainital', 'Pauri Garhwal', 'Pithoragarh', 'Rudraprayag', 'Tehri Garhwal', 'Udham Singh Nagar', 'Uttarkashi'],
  'West Bengal': ['Alipurduar', 'Bankura', 'Birbhum', 'Cooch Behar', 'Dakshin Dinajpur', 'Darjeeling', 'Hooghly', 'Howrah', 'Jalpaiguri', 'Jhargram', 'Kalimpong', 'Kolkata', 'Malda', 'Murshidabad', 'Nadia', 'North 24 Parganas', 'Paschim Bardhaman', 'Paschim Medinipur', 'Purba Bardhaman', 'Purba Medinipur', 'Purulia', 'South 24 Parganas', 'Uttar Dinajpur'],
  'Andaman and Nicobar Islands': ['Nicobar', 'North and Middle Andaman', 'South Andaman'],
  'Chandigarh': ['Chandigarh'],
  'Dadra and Nagar Haveli and Daman and Diu': ['Dadra and Nagar Haveli', 'Daman', 'Diu'],
  'Delhi': ['Central Delhi', 'East Delhi', 'New Delhi', 'North Delhi', 'North East Delhi', 'North West Delhi', 'Shahdara', 'South Delhi', 'South East Delhi', 'South West Delhi', 'West Delhi'],
  'Jammu and Kashmir': ['Anantnag', 'Bandipora', 'Baramulla', 'Budgam', 'Doda', 'Ganderbal', 'Jammu', 'Kathua', 'Kishtwar', 'Kulgam', 'Kupwara', 'Poonch', 'Pulwama', 'Rajouri', 'Ramban', 'Reasi', 'Samba', 'Shopian', 'Srinagar', 'Udhampur'],
  'Ladakh': ['Kargil', 'Leh'],
  'Lakshadweep': ['Lakshadweep'],
  'Puducherry': ['Karaikal', 'Mahe', 'Puducherry', 'Yanam']
};

export const DISTRICT_AREAS: Record<string, string[]> = {
  'South Delhi': ['Saket', 'Hauz Khas', 'Greater Kailash', 'Malviya Nagar', 'Green Park'],
  'New Delhi': ['Connaught Place', 'Chanakyapuri', 'Lodhi Colony'],
  'Mumbai City': ['Colaba', 'Worli', 'Parel', 'Dadra'],
  'Pune': ['Koregaon Park', 'Kothrud', 'Baner', 'Viman Nagar'],
  'Bangalore Urban': ['HSR Layout', 'Indiranagar', 'Koramangala', 'Whitefield', 'JP Nagar'],
  'Chennai': ['Adyar', 'T. Nagar', 'Mylapore', 'Anna Nagar']
};

export const FACILITIES_LIST = [
  'WiFi', 'Parking', 'Gym', 'Power Backup', 'Air Conditioning', 'CCTV', 'Lift', 'Security', 'Swimming Pool', 'Modular Kitchen'
];

export const MOCK_PROPERTIES = [
  {
    id: '1',
    landlordId: 'l1',
    title: 'Modern 2BHK in Saket',
    description: 'Beautiful sunlight-facing apartment near Metro Station. Quiet neighborhood with 24/7 security.',
    photos: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80'],
    videos: [],
    rent: 25000,
    deposit: 50000,
    location: {
      country: 'India',
      state: 'Delhi',
      district: 'South Delhi',
      city: 'Saket',
      area: 'Block J',
      address: 'J-123, Saket',
      landmark: 'Near DLF Avenue',
      houseNumber: '123',
      coordinates: { lat: 28.5244, lng: 77.2103 }
    },
    furnishing: 'Semi-furnished',
    tenantType: 'Both',
    foodPreference: 'Veg/Non-Veg',
    facilities: ['Parking', 'Security', 'Lift', 'WiFi'],
    createdAt: Date.now(),
    interestedCount: 5,
    reviews: []
  },
  {
    id: '2',
    landlordId: 'l2',
    title: 'Cozy Studio near HSR Layout',
    description: 'Perfect for bachelors working in nearby tech parks. Fully furnished with high-speed internet.',
    photos: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80'],
    videos: [],
    rent: 12000,
    deposit: 30000,
    location: {
      country: 'India',
      state: 'Karnataka',
      district: 'Bangalore Urban',
      city: 'HSR Layout',
      area: 'Sector 2',
      address: 'No 45, Sector 2',
      landmark: 'Near BDA Complex',
      houseNumber: '45',
      coordinates: { lat: 12.9141, lng: 77.6411 }
    },
    furnishing: 'Furnished',
    tenantType: 'Bachelor',
    foodPreference: 'Veg Only',
    facilities: ['WiFi', 'CCTV', 'Power Backup'],
    createdAt: Date.now() - 86400000,
    interestedCount: 12,
    reviews: []
  },
  {
    id: '3',
    landlordId: 'l3',
    title: 'Luxury 3BHK Penthouse',
    description: 'Spacious penthouse with a private terrace. Prime location in Koregaon Park.',
    photos: ['https://images.unsplash.com/photo-1600585154340-be6199bc3a07?auto=format&fit=crop&w=800&q=80'],
    videos: [],
    rent: 85000,
    deposit: 200000,
    location: {
      country: 'India',
      state: 'Maharashtra',
      district: 'Pune',
      city: 'Koregaon Park',
      area: 'Lane 7',
      address: 'Penthouse 1, Riverview',
      landmark: 'Near German Bakery',
      houseNumber: '1',
      coordinates: { lat: 18.5362, lng: 73.8940 }
    },
    furnishing: 'Furnished',
    tenantType: 'Family',
    foodPreference: 'Veg/Non-Veg',
    facilities: ['Swimming Pool', 'Gym', 'Parking', 'Modular Kitchen'],
    createdAt: Date.now() - 172800000,
    interestedCount: 3,
    reviews: []
  },
  {
    id: '4',
    landlordId: 'l4',
    title: 'Compact 1BHK in Andheri',
    description: 'Minimalist living for young professionals. Great connectivity to Western Express Highway.',
    photos: ['https://images.unsplash.com/photo-1536376074432-bf12178d1f4a?auto=format&fit=crop&w=800&q=80'],
    videos: [],
    rent: 35000,
    deposit: 100000,
    location: {
      country: 'India',
      state: 'Maharashtra',
      district: 'Mumbai Suburban',
      city: 'Andheri',
      area: 'West',
      address: 'Flat 402, Sunshine Apts',
      landmark: 'Near Shoppers Stop',
      houseNumber: '402',
      coordinates: { lat: 19.1136, lng: 72.8697 }
    },
    furnishing: 'Unfurnished',
    tenantType: 'Bachelor',
    foodPreference: 'Veg/Non-Veg',
    facilities: ['Lift', 'Security', 'Power Backup'],
    createdAt: Date.now() - 259200000,
    interestedCount: 8,
    reviews: []
  },
  {
    id: '5',
    landlordId: 'l5',
    title: 'Heritage Villa in Mysore',
    description: 'Experience the royal charm. Traditional architecture with modern internal amenities.',
    photos: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80'],
    videos: [],
    rent: 45000,
    deposit: 150000,
    location: {
      country: 'India',
      state: 'Karnataka',
      district: 'Mysore',
      city: 'Mysore',
      area: 'Jayalakshmipuram',
      address: '22/A, Heritage Enclave',
      landmark: 'Near Palace Ground',
      houseNumber: '22',
      coordinates: { lat: 12.2958, lng: 76.6394 }
    },
    furnishing: 'Semi-furnished',
    tenantType: 'Family',
    foodPreference: 'Veg Only',
    facilities: ['Parking', 'CCTV', 'Modular Kitchen'],
    createdAt: Date.now() - 345600000,
    interestedCount: 2,
    reviews: []
  },
  {
    id: '6',
    landlordId: 'l6',
    title: 'Bachelor Pad in Noida Sector 62',
    description: 'Walkable distance to major IT hubs. Fully serviced apartment with laundry facilities.',
    photos: ['https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80'],
    videos: [],
    rent: 15000,
    deposit: 30000,
    location: {
      country: 'India',
      state: 'Uttar Pradesh',
      district: 'Noida',
      city: 'Noida',
      area: 'Sector 62',
      address: 'Tower C, PG Heights',
      landmark: 'Near Stellar IT Park',
      houseNumber: 'C-501',
      coordinates: { lat: 28.6258, lng: 77.3639 }
    },
    furnishing: 'Furnished',
    tenantType: 'Bachelor',
    foodPreference: 'Veg/Non-Veg',
    facilities: ['WiFi', 'Power Backup', 'Gym'],
    createdAt: Date.now() - 432000000,
    interestedCount: 25,
    reviews: []
  },
  {
    id: '7',
    landlordId: 'l7',
    title: 'Sea Facing Apartment, Worli',
    description: 'Uninterrupted views of the Arabian Sea. Elite gated community with premium features.',
    photos: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80'],
    videos: [],
    rent: 120000,
    deposit: 500000,
    location: {
      country: 'India',
      state: 'Maharashtra',
      district: 'Mumbai City',
      city: 'Worli',
      area: 'Worli Sea Face',
      address: 'Floor 18, Ocean Crest',
      landmark: 'Near Sea Link',
      houseNumber: '1802',
      coordinates: { lat: 19.0000, lng: 72.8150 }
    },
    furnishing: 'Furnished',
    tenantType: 'Family',
    foodPreference: 'Veg/Non-Veg',
    facilities: ['Swimming Pool', 'Gym', 'Parking', 'CCTV', 'Lift'],
    createdAt: Date.now() - 518400000,
    interestedCount: 4,
    reviews: []
  },
  {
    id: '8',
    landlordId: 'l8',
    title: '1BHK Near Anna Nagar',
    description: 'Well-ventilated flat in a residential hotspot. Easy access to shops and parks.',
    photos: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80'],
    videos: [],
    rent: 18000,
    deposit: 60000,
    location: {
      country: 'India',
      state: 'Tamil Nadu',
      district: 'Chennai',
      city: 'Anna Nagar',
      area: 'Shanti Colony',
      address: '4th Avenue, Green Leaf',
      landmark: 'Near Tower Park',
      houseNumber: '44',
      coordinates: { lat: 13.0850, lng: 80.2101 }
    },
    furnishing: 'Semi-furnished',
    tenantType: 'Both',
    foodPreference: 'Veg Only',
    facilities: ['Parking', 'Security', 'Lift'],
    createdAt: Date.now() - 604800000,
    interestedCount: 7,
    reviews: []
  },
  {
    id: '9',
    landlordId: 'l9',
    title: 'Contemporary Flat in Salt Lake',
    description: 'Modern interiors with a touch of elegance. Located in the tech hub of Kolkata.',
    photos: ['https://images.unsplash.com/photo-1560448204-61dc36dc98c8?auto=format&fit=crop&w=800&q=80'],
    videos: [],
    rent: 28000,
    deposit: 75000,
    location: {
      country: 'India',
      state: 'West Bengal',
      district: 'Kolkata',
      city: 'Kolkata',
      area: 'Salt Lake Sector V',
      address: 'Block EP, IT Towers',
      landmark: 'Near Wipro Circle',
      houseNumber: 'EP-12',
      coordinates: { lat: 22.5726, lng: 88.4339 }
    },
    furnishing: 'Furnished',
    tenantType: 'Both',
    foodPreference: 'Veg/Non-Veg',
    facilities: ['WiFi', 'Power Backup', 'Air Conditioning'],
    createdAt: Date.now() - 691200000,
    interestedCount: 15,
    reviews: []
  },
  {
    id: '10',
    landlordId: 'l10',
    title: 'Studio Apartment, Ahmedabad',
    description: 'Perfect for students or solo travelers. Close to top universities and shopping hubs.',
    photos: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=80'],
    videos: [],
    rent: 9000,
    deposit: 20000,
    location: {
      country: 'India',
      state: 'Gujarat',
      district: 'Ahmedabad',
      city: 'Ahmedabad',
      area: 'Navrangpura',
      address: 'Flat 10, Student Haven',
      landmark: 'Near Gujarat University',
      houseNumber: '10',
      coordinates: { lat: 23.0373, lng: 72.5524 }
    },
    furnishing: 'Semi-furnished',
    tenantType: 'Bachelor',
    foodPreference: 'Veg Only',
    facilities: ['WiFi', 'CCTV'],
    createdAt: Date.now() - 777600000,
    interestedCount: 30,
    reviews: []
  }
];
